# Generated by Django 4.1.5 on 2023-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvetonchamp', '0003_alter_image_images_alter_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='product/images'),
        ),
    ]
