# Generated by Django 4.1.5 on 2023-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvetonchamp', '0005_product_img1_product_img2_product_img3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
